"""add_work_tasks

Revision ID: 2b2ee57f1bcf
Revises: 1de3344e33e4
Create Date: 2025-12-05 18:56:52.934784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2ee57f1bcf'
down_revision: Union[str, None] = '1de3344e33e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
